image: Visual Studio 2019

environment:
  PRJ_NAME: 'App'
  TEST_ASSEMBLY: '%PRJ_NAME%.Tests\bin\%PLATFORM%\%CONFIGURATION%\%PRJ_NAME%.Tests.dll'
  COVERALLS_REPO_TOKEN:
    secure: AA6BsNJ40iTf4N/1NmoRoweZcQZAU0kwkH+CDk/s8pR143KAQ/QxyKqvGv0f/47O

#branches:
#  only:
#  - master
#  - develop

skip_commits:
   files:
     - '**/*.md'

configuration:
  - Release
platform:
  - x64

#skip_tags: true
#skip_branch_with_pr: true

cache:
  - 'C:\ProgramData\chocolatey\bin -> appveyor.yml'
  - 'C:\ProgramData\chocolatey\lib -> appveyor.yml'
  - 'C:\Program Files (x86)\Inno Setup 6 -> appveyor.yml'
  
install:
  - dotnet tool install coveralls.net --global --version 1.0.0
  - choco install gitversion.portable -pre -y --version 5.2.4
  - choco install -y innosetup --version 6.0.4
  - set PATH="C:\Program Files (x86)\Inno Setup 6";%PATH%
  
before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  
build:
  project: '%PRJ_NAME%.sln'
  verbosity: minimal

test_script: 
  - cmd: >-
  
      %USERPROFILE%\.nuget\packages\opencover\4.7.922\tools\OpenCover.Console.exe -register:administrator -target:"%xunit20%\xunit.console.exe" -targetargs:"%TEST_ASSEMBLY% -appveyor -noshadow" -filter:"+[*]Saawsm.*.Tests*" -coverbytest:"*.Tests.dll" -output:".\coverage_%CONFIGURATION%-%PLATFORM%.xml"
        
      %USERPROFILE%\.dotnet\tools\csmacnz.Coveralls.exe --opencover -i "./coverage_%CONFIGURATION%-%PLATFORM%.xml" --serviceName AppVeyor --repoToken "%COVERALLS_REPO_TOKEN%"

artifacts:
  - path: 'coverage_%CONFIGURATION%-%PLATFORM%.xml'
    name: 'CodeCoverage_%CONFIGURATION%-%PLATFORM%'
  - path: '%PRJ_NAME%\bin\%PLATFORM%\%CONFIGURATION%\%PRJ_NAME%.exe'
    name: 'App_%CONFIGURATION%-%PLATFORM%'
    
deploy:
  - provider: GitHub
    release: $(GitVersion_SemVer)
    auth_token:
      secure: ifXlmVS0EJd5CrTa4LZrXpmCA1Ms84qO1shbmOQyrakTuwZH8yeC65+TrgLd7kKE
    artifact: 'App_%CONFIGURATION%-%PLATFORM%'
    on:
      branch: /v\d\.\d\.\d/
      configuration: Release
      APPVEYOR_REPO_TAG: true